# Generated by Django 4.2.11 on 2024-04-30 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileUpload', '0003_uploadedfile_file_name_uploadedfile_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_file', models.FileField(upload_to='spectrals/', verbose_name='DAT File')),
                ('hdr_file', models.FileField(upload_to='spectrals/', verbose_name='HDR File')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload Time')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectral_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
