# Generated by Django 4.2.11 on 2024-05-01 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0004_spectraldata_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='spectrals/', verbose_name='DAT File')),
            ],
        ),
        migrations.CreateModel(
            name='HdrFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='spectrals/', verbose_name='HDR File')),
            ],
        ),
        migrations.AlterField(
            model_name='spectraldata',
            name='dat_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectral_data_dat', to='fileUpload.datfile'),
        ),
        migrations.AlterField(
            model_name='spectraldata',
            name='hdr_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectral_data_hdr', to='fileUpload.hdrfile'),
        ),
    ]
