# Generated by Django 4.2.11 on 2024-05-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0006_datfile_file_name_datfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Original File Name'),
        ),
        migrations.AlterField(
            model_name='hdrfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Original File Name'),
        ),
    ]
