# Generated by Django 4.2.11 on 2024-05-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileProc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procrecord',
            name='dat_file',
        ),
    ]
