# Generated by Django 4.2.11 on 2024-04-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0002_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
