# Generated by Django 4.2.11 on 2024-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0003_rename_book_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
